//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("bienestarModel", "FK_ADJUNTO_ACTIVIDAD", "ACTIVIDAD", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SistemaBienestarEstudiantil.Models.ACTIVIDAD), "ADJUNTO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SistemaBienestarEstudiantil.Models.ADJUNTO), true)]
[assembly: EdmRelationshipAttribute("bienestarModel", "FK_ASISTENCIA_ALUMNO", "ALUMNO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SistemaBienestarEstudiantil.Models.ALUMNO), "ASISTENCIA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SistemaBienestarEstudiantil.Models.ASISTENCIA), true)]
[assembly: EdmRelationshipAttribute("bienestarModel", "FK_ASISTENCIA_GRUPO", "GRUPO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SistemaBienestarEstudiantil.Models.GRUPO), "ASISTENCIA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SistemaBienestarEstudiantil.Models.ASISTENCIA), true)]
[assembly: EdmRelationshipAttribute("bienestarModel", "FK_ROL_MODULO_MODULO1", "MODULO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SistemaBienestarEstudiantil.Models.MODULO), "ROL_MODULO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SistemaBienestarEstudiantil.Models.ROL_MODULO), true)]
[assembly: EdmRelationshipAttribute("bienestarModel", "FK_ROL_MODULO_ROL", "ROL", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SistemaBienestarEstudiantil.Models.ROL), "ROL_MODULO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SistemaBienestarEstudiantil.Models.ROL_MODULO), true)]
[assembly: EdmRelationshipAttribute("bienestarModel", "ACTIVIDAD_USUARIO", "ACTIVIDAD", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SistemaBienestarEstudiantil.Models.ACTIVIDAD), "USUARIO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SistemaBienestarEstudiantil.Models.USUARIO))]
[assembly: EdmRelationshipAttribute("bienestarModel", "GRUPO_ACTIVIDAD", "ACTIVIDAD", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SistemaBienestarEstudiantil.Models.ACTIVIDAD), "GRUPO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SistemaBienestarEstudiantil.Models.GRUPO))]
[assembly: EdmRelationshipAttribute("bienestarModel", "NIVEL_ALUMNO", "ALUMNO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SistemaBienestarEstudiantil.Models.ALUMNO), "NIVEL", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SistemaBienestarEstudiantil.Models.NIVEL))]
[assembly: EdmRelationshipAttribute("bienestarModel", "USUARIO_ROL", "ROL", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SistemaBienestarEstudiantil.Models.ROL), "USUARIO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SistemaBienestarEstudiantil.Models.USUARIO))]

#endregion

namespace SistemaBienestarEstudiantil.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class bienestarEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto bienestarEntities usando la cadena de conexión encontrada en la sección 'bienestarEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public bienestarEntities() : base("name=bienestarEntities", "bienestarEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto bienestarEntities.
        /// </summary>
        public bienestarEntities(string connectionString) : base(connectionString, "bienestarEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto bienestarEntities.
        /// </summary>
        public bienestarEntities(EntityConnection connection) : base(connection, "bienestarEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<ACTIVIDAD> ACTIVIDADs
        {
            get
            {
                if ((_ACTIVIDADs == null))
                {
                    _ACTIVIDADs = base.CreateObjectSet<ACTIVIDAD>("ACTIVIDADs");
                }
                return _ACTIVIDADs;
            }
        }
        private ObjectSet<ACTIVIDAD> _ACTIVIDADs;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<ADJUNTO> ADJUNTOes
        {
            get
            {
                if ((_ADJUNTOes == null))
                {
                    _ADJUNTOes = base.CreateObjectSet<ADJUNTO>("ADJUNTOes");
                }
                return _ADJUNTOes;
            }
        }
        private ObjectSet<ADJUNTO> _ADJUNTOes;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<ALUMNO> ALUMNOes
        {
            get
            {
                if ((_ALUMNOes == null))
                {
                    _ALUMNOes = base.CreateObjectSet<ALUMNO>("ALUMNOes");
                }
                return _ALUMNOes;
            }
        }
        private ObjectSet<ALUMNO> _ALUMNOes;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<ASISTENCIA> ASISTENCIAs
        {
            get
            {
                if ((_ASISTENCIAs == null))
                {
                    _ASISTENCIAs = base.CreateObjectSet<ASISTENCIA>("ASISTENCIAs");
                }
                return _ASISTENCIAs;
            }
        }
        private ObjectSet<ASISTENCIA> _ASISTENCIAs;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<GRUPO> GRUPOes
        {
            get
            {
                if ((_GRUPOes == null))
                {
                    _GRUPOes = base.CreateObjectSet<GRUPO>("GRUPOes");
                }
                return _GRUPOes;
            }
        }
        private ObjectSet<GRUPO> _GRUPOes;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<MODULO> MODULOes
        {
            get
            {
                if ((_MODULOes == null))
                {
                    _MODULOes = base.CreateObjectSet<MODULO>("MODULOes");
                }
                return _MODULOes;
            }
        }
        private ObjectSet<MODULO> _MODULOes;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<NIVEL> NIVELs
        {
            get
            {
                if ((_NIVELs == null))
                {
                    _NIVELs = base.CreateObjectSet<NIVEL>("NIVELs");
                }
                return _NIVELs;
            }
        }
        private ObjectSet<NIVEL> _NIVELs;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<ROL> ROLs
        {
            get
            {
                if ((_ROLs == null))
                {
                    _ROLs = base.CreateObjectSet<ROL>("ROLs");
                }
                return _ROLs;
            }
        }
        private ObjectSet<ROL> _ROLs;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<ROL_MODULO> ROL_MODULO
        {
            get
            {
                if ((_ROL_MODULO == null))
                {
                    _ROL_MODULO = base.CreateObjectSet<ROL_MODULO>("ROL_MODULO");
                }
                return _ROL_MODULO;
            }
        }
        private ObjectSet<ROL_MODULO> _ROL_MODULO;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<USUARIO> USUARIOs
        {
            get
            {
                if ((_USUARIOs == null))
                {
                    _USUARIOs = base.CreateObjectSet<USUARIO>("USUARIOs");
                }
                return _USUARIOs;
            }
        }
        private ObjectSet<USUARIO> _USUARIOs;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ACTIVIDADs. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToACTIVIDADs(ACTIVIDAD aCTIVIDAD)
        {
            base.AddObject("ACTIVIDADs", aCTIVIDAD);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ADJUNTOes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToADJUNTOes(ADJUNTO aDJUNTO)
        {
            base.AddObject("ADJUNTOes", aDJUNTO);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ALUMNOes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToALUMNOes(ALUMNO aLUMNO)
        {
            base.AddObject("ALUMNOes", aLUMNO);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ASISTENCIAs. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToASISTENCIAs(ASISTENCIA aSISTENCIA)
        {
            base.AddObject("ASISTENCIAs", aSISTENCIA);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet GRUPOes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToGRUPOes(GRUPO gRUPO)
        {
            base.AddObject("GRUPOes", gRUPO);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet MODULOes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToMODULOes(MODULO mODULO)
        {
            base.AddObject("MODULOes", mODULO);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet NIVELs. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToNIVELs(NIVEL nIVEL)
        {
            base.AddObject("NIVELs", nIVEL);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ROLs. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToROLs(ROL rOL)
        {
            base.AddObject("ROLs", rOL);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ROL_MODULO. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToROL_MODULO(ROL_MODULO rOL_MODULO)
        {
            base.AddObject("ROL_MODULO", rOL_MODULO);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet sysdiagrams. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet USUARIOs. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUSUARIOs(USUARIO uSUARIO)
        {
            base.AddObject("USUARIOs", uSUARIO);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bienestarModel", Name="ACTIVIDAD")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ACTIVIDAD : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto ACTIVIDAD.
        /// </summary>
        /// <param name="cODIGOACTIVIDAD">Valor inicial de la propiedad CODIGOACTIVIDAD.</param>
        /// <param name="nOMBREACTIVIDAD">Valor inicial de la propiedad NOMBREACTIVIDAD.</param>
        /// <param name="eSTADOACTIVIDAD">Valor inicial de la propiedad ESTADOACTIVIDAD.</param>
        public static ACTIVIDAD CreateACTIVIDAD(global::System.Decimal cODIGOACTIVIDAD, global::System.String nOMBREACTIVIDAD, global::System.Boolean eSTADOACTIVIDAD)
        {
            ACTIVIDAD aCTIVIDAD = new ACTIVIDAD();
            aCTIVIDAD.CODIGOACTIVIDAD = cODIGOACTIVIDAD;
            aCTIVIDAD.NOMBREACTIVIDAD = nOMBREACTIVIDAD;
            aCTIVIDAD.ESTADOACTIVIDAD = eSTADOACTIVIDAD;
            return aCTIVIDAD;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CODIGOACTIVIDAD
        {
            get
            {
                return _CODIGOACTIVIDAD;
            }
            set
            {
                if (_CODIGOACTIVIDAD != value)
                {
                    OnCODIGOACTIVIDADChanging(value);
                    ReportPropertyChanging("CODIGOACTIVIDAD");
                    _CODIGOACTIVIDAD = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CODIGOACTIVIDAD");
                    OnCODIGOACTIVIDADChanged();
                }
            }
        }
        private global::System.Decimal _CODIGOACTIVIDAD;
        partial void OnCODIGOACTIVIDADChanging(global::System.Decimal value);
        partial void OnCODIGOACTIVIDADChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMBREACTIVIDAD
        {
            get
            {
                return _NOMBREACTIVIDAD;
            }
            set
            {
                OnNOMBREACTIVIDADChanging(value);
                ReportPropertyChanging("NOMBREACTIVIDAD");
                _NOMBREACTIVIDAD = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMBREACTIVIDAD");
                OnNOMBREACTIVIDADChanged();
            }
        }
        private global::System.String _NOMBREACTIVIDAD;
        partial void OnNOMBREACTIVIDADChanging(global::System.String value);
        partial void OnNOMBREACTIVIDADChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FECHAACTIVIDAD
        {
            get
            {
                return _FECHAACTIVIDAD;
            }
            set
            {
                OnFECHAACTIVIDADChanging(value);
                ReportPropertyChanging("FECHAACTIVIDAD");
                _FECHAACTIVIDAD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FECHAACTIVIDAD");
                OnFECHAACTIVIDADChanged();
            }
        }
        private Nullable<global::System.DateTime> _FECHAACTIVIDAD;
        partial void OnFECHAACTIVIDADChanging(Nullable<global::System.DateTime> value);
        partial void OnFECHAACTIVIDADChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ESTADOACTIVIDAD
        {
            get
            {
                return _ESTADOACTIVIDAD;
            }
            set
            {
                OnESTADOACTIVIDADChanging(value);
                ReportPropertyChanging("ESTADOACTIVIDAD");
                _ESTADOACTIVIDAD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ESTADOACTIVIDAD");
                OnESTADOACTIVIDADChanged();
            }
        }
        private global::System.Boolean _ESTADOACTIVIDAD;
        partial void OnESTADOACTIVIDADChanging(global::System.Boolean value);
        partial void OnESTADOACTIVIDADChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OBSERVACIONACTIVIDAD
        {
            get
            {
                return _OBSERVACIONACTIVIDAD;
            }
            set
            {
                OnOBSERVACIONACTIVIDADChanging(value);
                ReportPropertyChanging("OBSERVACIONACTIVIDAD");
                _OBSERVACIONACTIVIDAD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OBSERVACIONACTIVIDAD");
                OnOBSERVACIONACTIVIDADChanged();
            }
        }
        private global::System.String _OBSERVACIONACTIVIDAD;
        partial void OnOBSERVACIONACTIVIDADChanging(global::System.String value);
        partial void OnOBSERVACIONACTIVIDADChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("bienestarModel", "FK_ADJUNTO_ACTIVIDAD", "ADJUNTO")]
        public EntityCollection<ADJUNTO> ADJUNTOes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ADJUNTO>("bienestarModel.FK_ADJUNTO_ACTIVIDAD", "ADJUNTO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ADJUNTO>("bienestarModel.FK_ADJUNTO_ACTIVIDAD", "ADJUNTO", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("bienestarModel", "ACTIVIDAD_USUARIO", "USUARIO")]
        public EntityCollection<USUARIO> USUARIOs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<USUARIO>("bienestarModel.ACTIVIDAD_USUARIO", "USUARIO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<USUARIO>("bienestarModel.ACTIVIDAD_USUARIO", "USUARIO", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("bienestarModel", "GRUPO_ACTIVIDAD", "GRUPO")]
        public EntityCollection<GRUPO> GRUPOes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GRUPO>("bienestarModel.GRUPO_ACTIVIDAD", "GRUPO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GRUPO>("bienestarModel.GRUPO_ACTIVIDAD", "GRUPO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bienestarModel", Name="ADJUNTO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ADJUNTO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto ADJUNTO.
        /// </summary>
        /// <param name="cODIGOADJUNTO">Valor inicial de la propiedad CODIGOADJUNTO.</param>
        /// <param name="cODIGOACTIVIDAD">Valor inicial de la propiedad CODIGOACTIVIDAD.</param>
        /// <param name="aDJUNTO1">Valor inicial de la propiedad ADJUNTO1.</param>
        /// <param name="eSTADOADJUNTO">Valor inicial de la propiedad ESTADOADJUNTO.</param>
        public static ADJUNTO CreateADJUNTO(global::System.Decimal cODIGOADJUNTO, global::System.Decimal cODIGOACTIVIDAD, global::System.Byte[] aDJUNTO1, global::System.Boolean eSTADOADJUNTO)
        {
            ADJUNTO aDJUNTO = new ADJUNTO();
            aDJUNTO.CODIGOADJUNTO = cODIGOADJUNTO;
            aDJUNTO.CODIGOACTIVIDAD = cODIGOACTIVIDAD;
            aDJUNTO.ADJUNTO1 = aDJUNTO1;
            aDJUNTO.ESTADOADJUNTO = eSTADOADJUNTO;
            return aDJUNTO;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CODIGOADJUNTO
        {
            get
            {
                return _CODIGOADJUNTO;
            }
            set
            {
                if (_CODIGOADJUNTO != value)
                {
                    OnCODIGOADJUNTOChanging(value);
                    ReportPropertyChanging("CODIGOADJUNTO");
                    _CODIGOADJUNTO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CODIGOADJUNTO");
                    OnCODIGOADJUNTOChanged();
                }
            }
        }
        private global::System.Decimal _CODIGOADJUNTO;
        partial void OnCODIGOADJUNTOChanging(global::System.Decimal value);
        partial void OnCODIGOADJUNTOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CODIGOACTIVIDAD
        {
            get
            {
                return _CODIGOACTIVIDAD;
            }
            set
            {
                if (_CODIGOACTIVIDAD != value)
                {
                    OnCODIGOACTIVIDADChanging(value);
                    ReportPropertyChanging("CODIGOACTIVIDAD");
                    _CODIGOACTIVIDAD = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CODIGOACTIVIDAD");
                    OnCODIGOACTIVIDADChanged();
                }
            }
        }
        private global::System.Decimal _CODIGOACTIVIDAD;
        partial void OnCODIGOACTIVIDADChanging(global::System.Decimal value);
        partial void OnCODIGOACTIVIDADChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] ADJUNTO1
        {
            get
            {
                return StructuralObject.GetValidValue(_ADJUNTO1);
            }
            set
            {
                OnADJUNTO1Changing(value);
                ReportPropertyChanging("ADJUNTO1");
                _ADJUNTO1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ADJUNTO1");
                OnADJUNTO1Changed();
            }
        }
        private global::System.Byte[] _ADJUNTO1;
        partial void OnADJUNTO1Changing(global::System.Byte[] value);
        partial void OnADJUNTO1Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NOMBREADJUNTO
        {
            get
            {
                return _NOMBREADJUNTO;
            }
            set
            {
                OnNOMBREADJUNTOChanging(value);
                ReportPropertyChanging("NOMBREADJUNTO");
                _NOMBREADJUNTO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NOMBREADJUNTO");
                OnNOMBREADJUNTOChanged();
            }
        }
        private global::System.String _NOMBREADJUNTO;
        partial void OnNOMBREADJUNTOChanging(global::System.String value);
        partial void OnNOMBREADJUNTOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ESTADOADJUNTO
        {
            get
            {
                return _ESTADOADJUNTO;
            }
            set
            {
                OnESTADOADJUNTOChanging(value);
                ReportPropertyChanging("ESTADOADJUNTO");
                _ESTADOADJUNTO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ESTADOADJUNTO");
                OnESTADOADJUNTOChanged();
            }
        }
        private global::System.Boolean _ESTADOADJUNTO;
        partial void OnESTADOADJUNTOChanging(global::System.Boolean value);
        partial void OnESTADOADJUNTOChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("bienestarModel", "FK_ADJUNTO_ACTIVIDAD", "ACTIVIDAD")]
        public ACTIVIDAD ACTIVIDAD
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ACTIVIDAD>("bienestarModel.FK_ADJUNTO_ACTIVIDAD", "ACTIVIDAD").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ACTIVIDAD>("bienestarModel.FK_ADJUNTO_ACTIVIDAD", "ACTIVIDAD").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ACTIVIDAD> ACTIVIDADReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ACTIVIDAD>("bienestarModel.FK_ADJUNTO_ACTIVIDAD", "ACTIVIDAD");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ACTIVIDAD>("bienestarModel.FK_ADJUNTO_ACTIVIDAD", "ACTIVIDAD", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bienestarModel", Name="ALUMNO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ALUMNO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto ALUMNO.
        /// </summary>
        /// <param name="cODIGOALUMNO">Valor inicial de la propiedad CODIGOALUMNO.</param>
        /// <param name="nOMBREALUMNO">Valor inicial de la propiedad NOMBREALUMNO.</param>
        public static ALUMNO CreateALUMNO(global::System.Decimal cODIGOALUMNO, global::System.String nOMBREALUMNO)
        {
            ALUMNO aLUMNO = new ALUMNO();
            aLUMNO.CODIGOALUMNO = cODIGOALUMNO;
            aLUMNO.NOMBREALUMNO = nOMBREALUMNO;
            return aLUMNO;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CODIGOALUMNO
        {
            get
            {
                return _CODIGOALUMNO;
            }
            set
            {
                if (_CODIGOALUMNO != value)
                {
                    OnCODIGOALUMNOChanging(value);
                    ReportPropertyChanging("CODIGOALUMNO");
                    _CODIGOALUMNO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CODIGOALUMNO");
                    OnCODIGOALUMNOChanged();
                }
            }
        }
        private global::System.Decimal _CODIGOALUMNO;
        partial void OnCODIGOALUMNOChanging(global::System.Decimal value);
        partial void OnCODIGOALUMNOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMBREALUMNO
        {
            get
            {
                return _NOMBREALUMNO;
            }
            set
            {
                OnNOMBREALUMNOChanging(value);
                ReportPropertyChanging("NOMBREALUMNO");
                _NOMBREALUMNO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMBREALUMNO");
                OnNOMBREALUMNOChanged();
            }
        }
        private global::System.String _NOMBREALUMNO;
        partial void OnNOMBREALUMNOChanging(global::System.String value);
        partial void OnNOMBREALUMNOChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("bienestarModel", "FK_ASISTENCIA_ALUMNO", "ASISTENCIA")]
        public EntityCollection<ASISTENCIA> ASISTENCIAs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ASISTENCIA>("bienestarModel.FK_ASISTENCIA_ALUMNO", "ASISTENCIA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ASISTENCIA>("bienestarModel.FK_ASISTENCIA_ALUMNO", "ASISTENCIA", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("bienestarModel", "NIVEL_ALUMNO", "NIVEL")]
        public EntityCollection<NIVEL> NIVELs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<NIVEL>("bienestarModel.NIVEL_ALUMNO", "NIVEL");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<NIVEL>("bienestarModel.NIVEL_ALUMNO", "NIVEL", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bienestarModel", Name="ASISTENCIA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ASISTENCIA : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto ASISTENCIA.
        /// </summary>
        /// <param name="cODIGOASISTENCIA">Valor inicial de la propiedad CODIGOASISTENCIA.</param>
        /// <param name="cODIGOGRUPO">Valor inicial de la propiedad CODIGOGRUPO.</param>
        /// <param name="cODIGOALUMNO">Valor inicial de la propiedad CODIGOALUMNO.</param>
        /// <param name="aSISTENCIA1">Valor inicial de la propiedad ASISTENCIA1.</param>
        public static ASISTENCIA CreateASISTENCIA(global::System.Decimal cODIGOASISTENCIA, global::System.Decimal cODIGOGRUPO, global::System.Decimal cODIGOALUMNO, global::System.Boolean aSISTENCIA1)
        {
            ASISTENCIA aSISTENCIA = new ASISTENCIA();
            aSISTENCIA.CODIGOASISTENCIA = cODIGOASISTENCIA;
            aSISTENCIA.CODIGOGRUPO = cODIGOGRUPO;
            aSISTENCIA.CODIGOALUMNO = cODIGOALUMNO;
            aSISTENCIA.ASISTENCIA1 = aSISTENCIA1;
            return aSISTENCIA;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CODIGOASISTENCIA
        {
            get
            {
                return _CODIGOASISTENCIA;
            }
            set
            {
                if (_CODIGOASISTENCIA != value)
                {
                    OnCODIGOASISTENCIAChanging(value);
                    ReportPropertyChanging("CODIGOASISTENCIA");
                    _CODIGOASISTENCIA = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CODIGOASISTENCIA");
                    OnCODIGOASISTENCIAChanged();
                }
            }
        }
        private global::System.Decimal _CODIGOASISTENCIA;
        partial void OnCODIGOASISTENCIAChanging(global::System.Decimal value);
        partial void OnCODIGOASISTENCIAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CODIGOGRUPO
        {
            get
            {
                return _CODIGOGRUPO;
            }
            set
            {
                if (_CODIGOGRUPO != value)
                {
                    OnCODIGOGRUPOChanging(value);
                    ReportPropertyChanging("CODIGOGRUPO");
                    _CODIGOGRUPO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CODIGOGRUPO");
                    OnCODIGOGRUPOChanged();
                }
            }
        }
        private global::System.Decimal _CODIGOGRUPO;
        partial void OnCODIGOGRUPOChanging(global::System.Decimal value);
        partial void OnCODIGOGRUPOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CODIGOALUMNO
        {
            get
            {
                return _CODIGOALUMNO;
            }
            set
            {
                if (_CODIGOALUMNO != value)
                {
                    OnCODIGOALUMNOChanging(value);
                    ReportPropertyChanging("CODIGOALUMNO");
                    _CODIGOALUMNO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CODIGOALUMNO");
                    OnCODIGOALUMNOChanged();
                }
            }
        }
        private global::System.Decimal _CODIGOALUMNO;
        partial void OnCODIGOALUMNOChanging(global::System.Decimal value);
        partial void OnCODIGOALUMNOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ASISTENCIA1
        {
            get
            {
                return _ASISTENCIA1;
            }
            set
            {
                OnASISTENCIA1Changing(value);
                ReportPropertyChanging("ASISTENCIA1");
                _ASISTENCIA1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ASISTENCIA1");
                OnASISTENCIA1Changed();
            }
        }
        private global::System.Boolean _ASISTENCIA1;
        partial void OnASISTENCIA1Changing(global::System.Boolean value);
        partial void OnASISTENCIA1Changed();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("bienestarModel", "FK_ASISTENCIA_ALUMNO", "ALUMNO")]
        public ALUMNO ALUMNO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ALUMNO>("bienestarModel.FK_ASISTENCIA_ALUMNO", "ALUMNO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ALUMNO>("bienestarModel.FK_ASISTENCIA_ALUMNO", "ALUMNO").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ALUMNO> ALUMNOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ALUMNO>("bienestarModel.FK_ASISTENCIA_ALUMNO", "ALUMNO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ALUMNO>("bienestarModel.FK_ASISTENCIA_ALUMNO", "ALUMNO", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("bienestarModel", "FK_ASISTENCIA_GRUPO", "GRUPO")]
        public GRUPO GRUPO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GRUPO>("bienestarModel.FK_ASISTENCIA_GRUPO", "GRUPO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GRUPO>("bienestarModel.FK_ASISTENCIA_GRUPO", "GRUPO").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GRUPO> GRUPOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GRUPO>("bienestarModel.FK_ASISTENCIA_GRUPO", "GRUPO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GRUPO>("bienestarModel.FK_ASISTENCIA_GRUPO", "GRUPO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bienestarModel", Name="GRUPO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GRUPO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto GRUPO.
        /// </summary>
        /// <param name="cODIGOGRUPO">Valor inicial de la propiedad CODIGOGRUPO.</param>
        /// <param name="nIVELGRUPO">Valor inicial de la propiedad NIVELGRUPO.</param>
        /// <param name="eSTADOGRUPO">Valor inicial de la propiedad ESTADOGRUPO.</param>
        public static GRUPO CreateGRUPO(global::System.Decimal cODIGOGRUPO, global::System.String nIVELGRUPO, global::System.Boolean eSTADOGRUPO)
        {
            GRUPO gRUPO = new GRUPO();
            gRUPO.CODIGOGRUPO = cODIGOGRUPO;
            gRUPO.NIVELGRUPO = nIVELGRUPO;
            gRUPO.ESTADOGRUPO = eSTADOGRUPO;
            return gRUPO;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CODIGOGRUPO
        {
            get
            {
                return _CODIGOGRUPO;
            }
            set
            {
                if (_CODIGOGRUPO != value)
                {
                    OnCODIGOGRUPOChanging(value);
                    ReportPropertyChanging("CODIGOGRUPO");
                    _CODIGOGRUPO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CODIGOGRUPO");
                    OnCODIGOGRUPOChanged();
                }
            }
        }
        private global::System.Decimal _CODIGOGRUPO;
        partial void OnCODIGOGRUPOChanging(global::System.Decimal value);
        partial void OnCODIGOGRUPOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NIVELGRUPO
        {
            get
            {
                return _NIVELGRUPO;
            }
            set
            {
                OnNIVELGRUPOChanging(value);
                ReportPropertyChanging("NIVELGRUPO");
                _NIVELGRUPO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NIVELGRUPO");
                OnNIVELGRUPOChanged();
            }
        }
        private global::System.String _NIVELGRUPO;
        partial void OnNIVELGRUPOChanging(global::System.String value);
        partial void OnNIVELGRUPOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PARALELOGRUPO
        {
            get
            {
                return _PARALELOGRUPO;
            }
            set
            {
                OnPARALELOGRUPOChanging(value);
                ReportPropertyChanging("PARALELOGRUPO");
                _PARALELOGRUPO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PARALELOGRUPO");
                OnPARALELOGRUPOChanged();
            }
        }
        private global::System.String _PARALELOGRUPO;
        partial void OnPARALELOGRUPOChanging(global::System.String value);
        partial void OnPARALELOGRUPOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MODALIDADGRUPO
        {
            get
            {
                return _MODALIDADGRUPO;
            }
            set
            {
                OnMODALIDADGRUPOChanging(value);
                ReportPropertyChanging("MODALIDADGRUPO");
                _MODALIDADGRUPO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MODALIDADGRUPO");
                OnMODALIDADGRUPOChanged();
            }
        }
        private global::System.String _MODALIDADGRUPO;
        partial void OnMODALIDADGRUPOChanging(global::System.String value);
        partial void OnMODALIDADGRUPOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ESTADOGRUPO
        {
            get
            {
                return _ESTADOGRUPO;
            }
            set
            {
                OnESTADOGRUPOChanging(value);
                ReportPropertyChanging("ESTADOGRUPO");
                _ESTADOGRUPO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ESTADOGRUPO");
                OnESTADOGRUPOChanged();
            }
        }
        private global::System.Boolean _ESTADOGRUPO;
        partial void OnESTADOGRUPOChanging(global::System.Boolean value);
        partial void OnESTADOGRUPOChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("bienestarModel", "FK_ASISTENCIA_GRUPO", "ASISTENCIA")]
        public EntityCollection<ASISTENCIA> ASISTENCIAs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ASISTENCIA>("bienestarModel.FK_ASISTENCIA_GRUPO", "ASISTENCIA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ASISTENCIA>("bienestarModel.FK_ASISTENCIA_GRUPO", "ASISTENCIA", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("bienestarModel", "GRUPO_ACTIVIDAD", "ACTIVIDAD")]
        public EntityCollection<ACTIVIDAD> ACTIVIDADs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ACTIVIDAD>("bienestarModel.GRUPO_ACTIVIDAD", "ACTIVIDAD");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ACTIVIDAD>("bienestarModel.GRUPO_ACTIVIDAD", "ACTIVIDAD", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bienestarModel", Name="MODULO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MODULO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto MODULO.
        /// </summary>
        /// <param name="cODIGOMODULO">Valor inicial de la propiedad CODIGOMODULO.</param>
        /// <param name="nOMBREMODULO">Valor inicial de la propiedad NOMBREMODULO.</param>
        /// <param name="eNLACEMODULO">Valor inicial de la propiedad ENLACEMODULO.</param>
        /// <param name="eSTADOROL">Valor inicial de la propiedad ESTADOROL.</param>
        public static MODULO CreateMODULO(global::System.Decimal cODIGOMODULO, global::System.String nOMBREMODULO, global::System.String eNLACEMODULO, global::System.Boolean eSTADOROL)
        {
            MODULO mODULO = new MODULO();
            mODULO.CODIGOMODULO = cODIGOMODULO;
            mODULO.NOMBREMODULO = nOMBREMODULO;
            mODULO.ENLACEMODULO = eNLACEMODULO;
            mODULO.ESTADOROL = eSTADOROL;
            return mODULO;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CODIGOMODULO
        {
            get
            {
                return _CODIGOMODULO;
            }
            set
            {
                if (_CODIGOMODULO != value)
                {
                    OnCODIGOMODULOChanging(value);
                    ReportPropertyChanging("CODIGOMODULO");
                    _CODIGOMODULO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CODIGOMODULO");
                    OnCODIGOMODULOChanged();
                }
            }
        }
        private global::System.Decimal _CODIGOMODULO;
        partial void OnCODIGOMODULOChanging(global::System.Decimal value);
        partial void OnCODIGOMODULOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMBREMODULO
        {
            get
            {
                return _NOMBREMODULO;
            }
            set
            {
                OnNOMBREMODULOChanging(value);
                ReportPropertyChanging("NOMBREMODULO");
                _NOMBREMODULO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMBREMODULO");
                OnNOMBREMODULOChanged();
            }
        }
        private global::System.String _NOMBREMODULO;
        partial void OnNOMBREMODULOChanging(global::System.String value);
        partial void OnNOMBREMODULOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ENLACEMODULO
        {
            get
            {
                return _ENLACEMODULO;
            }
            set
            {
                OnENLACEMODULOChanging(value);
                ReportPropertyChanging("ENLACEMODULO");
                _ENLACEMODULO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ENLACEMODULO");
                OnENLACEMODULOChanged();
            }
        }
        private global::System.String _ENLACEMODULO;
        partial void OnENLACEMODULOChanging(global::System.String value);
        partial void OnENLACEMODULOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ESTADOROL
        {
            get
            {
                return _ESTADOROL;
            }
            set
            {
                OnESTADOROLChanging(value);
                ReportPropertyChanging("ESTADOROL");
                _ESTADOROL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ESTADOROL");
                OnESTADOROLChanged();
            }
        }
        private global::System.Boolean _ESTADOROL;
        partial void OnESTADOROLChanging(global::System.Boolean value);
        partial void OnESTADOROLChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("bienestarModel", "FK_ROL_MODULO_MODULO1", "ROL_MODULO")]
        public EntityCollection<ROL_MODULO> ROL_MODULO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ROL_MODULO>("bienestarModel.FK_ROL_MODULO_MODULO1", "ROL_MODULO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ROL_MODULO>("bienestarModel.FK_ROL_MODULO_MODULO1", "ROL_MODULO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bienestarModel", Name="NIVEL")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NIVEL : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto NIVEL.
        /// </summary>
        /// <param name="cODIGONIVEL">Valor inicial de la propiedad CODIGONIVEL.</param>
        /// <param name="nOMBRENIVEL">Valor inicial de la propiedad NOMBRENIVEL.</param>
        public static NIVEL CreateNIVEL(global::System.Decimal cODIGONIVEL, global::System.String nOMBRENIVEL)
        {
            NIVEL nIVEL = new NIVEL();
            nIVEL.CODIGONIVEL = cODIGONIVEL;
            nIVEL.NOMBRENIVEL = nOMBRENIVEL;
            return nIVEL;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CODIGONIVEL
        {
            get
            {
                return _CODIGONIVEL;
            }
            set
            {
                if (_CODIGONIVEL != value)
                {
                    OnCODIGONIVELChanging(value);
                    ReportPropertyChanging("CODIGONIVEL");
                    _CODIGONIVEL = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CODIGONIVEL");
                    OnCODIGONIVELChanged();
                }
            }
        }
        private global::System.Decimal _CODIGONIVEL;
        partial void OnCODIGONIVELChanging(global::System.Decimal value);
        partial void OnCODIGONIVELChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMBRENIVEL
        {
            get
            {
                return _NOMBRENIVEL;
            }
            set
            {
                OnNOMBRENIVELChanging(value);
                ReportPropertyChanging("NOMBRENIVEL");
                _NOMBRENIVEL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMBRENIVEL");
                OnNOMBRENIVELChanged();
            }
        }
        private global::System.String _NOMBRENIVEL;
        partial void OnNOMBRENIVELChanging(global::System.String value);
        partial void OnNOMBRENIVELChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("bienestarModel", "NIVEL_ALUMNO", "ALUMNO")]
        public EntityCollection<ALUMNO> ALUMNOes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ALUMNO>("bienestarModel.NIVEL_ALUMNO", "ALUMNO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ALUMNO>("bienestarModel.NIVEL_ALUMNO", "ALUMNO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bienestarModel", Name="ROL")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ROL : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto ROL.
        /// </summary>
        /// <param name="cODIGOROL">Valor inicial de la propiedad CODIGOROL.</param>
        /// <param name="nOMBREROL">Valor inicial de la propiedad NOMBREROL.</param>
        /// <param name="eSTADOROL">Valor inicial de la propiedad ESTADOROL.</param>
        public static ROL CreateROL(global::System.Decimal cODIGOROL, global::System.String nOMBREROL, global::System.Boolean eSTADOROL)
        {
            ROL rOL = new ROL();
            rOL.CODIGOROL = cODIGOROL;
            rOL.NOMBREROL = nOMBREROL;
            rOL.ESTADOROL = eSTADOROL;
            return rOL;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CODIGOROL
        {
            get
            {
                return _CODIGOROL;
            }
            set
            {
                if (_CODIGOROL != value)
                {
                    OnCODIGOROLChanging(value);
                    ReportPropertyChanging("CODIGOROL");
                    _CODIGOROL = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CODIGOROL");
                    OnCODIGOROLChanged();
                }
            }
        }
        private global::System.Decimal _CODIGOROL;
        partial void OnCODIGOROLChanging(global::System.Decimal value);
        partial void OnCODIGOROLChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMBREROL
        {
            get
            {
                return _NOMBREROL;
            }
            set
            {
                OnNOMBREROLChanging(value);
                ReportPropertyChanging("NOMBREROL");
                _NOMBREROL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMBREROL");
                OnNOMBREROLChanged();
            }
        }
        private global::System.String _NOMBREROL;
        partial void OnNOMBREROLChanging(global::System.String value);
        partial void OnNOMBREROLChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ESTADOROL
        {
            get
            {
                return _ESTADOROL;
            }
            set
            {
                OnESTADOROLChanging(value);
                ReportPropertyChanging("ESTADOROL");
                _ESTADOROL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ESTADOROL");
                OnESTADOROLChanged();
            }
        }
        private global::System.Boolean _ESTADOROL;
        partial void OnESTADOROLChanging(global::System.Boolean value);
        partial void OnESTADOROLChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("bienestarModel", "FK_ROL_MODULO_ROL", "ROL_MODULO")]
        public EntityCollection<ROL_MODULO> ROL_MODULO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ROL_MODULO>("bienestarModel.FK_ROL_MODULO_ROL", "ROL_MODULO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ROL_MODULO>("bienestarModel.FK_ROL_MODULO_ROL", "ROL_MODULO", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("bienestarModel", "USUARIO_ROL", "USUARIO")]
        public EntityCollection<USUARIO> USUARIOs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<USUARIO>("bienestarModel.USUARIO_ROL", "USUARIO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<USUARIO>("bienestarModel.USUARIO_ROL", "USUARIO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bienestarModel", Name="ROL_MODULO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ROL_MODULO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto ROL_MODULO.
        /// </summary>
        /// <param name="cODIGOROL">Valor inicial de la propiedad CODIGOROL.</param>
        /// <param name="cODIGOMODULO">Valor inicial de la propiedad CODIGOMODULO.</param>
        public static ROL_MODULO CreateROL_MODULO(global::System.Decimal cODIGOROL, global::System.Decimal cODIGOMODULO)
        {
            ROL_MODULO rOL_MODULO = new ROL_MODULO();
            rOL_MODULO.CODIGOROL = cODIGOROL;
            rOL_MODULO.CODIGOMODULO = cODIGOMODULO;
            return rOL_MODULO;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CODIGOROL
        {
            get
            {
                return _CODIGOROL;
            }
            set
            {
                if (_CODIGOROL != value)
                {
                    OnCODIGOROLChanging(value);
                    ReportPropertyChanging("CODIGOROL");
                    _CODIGOROL = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CODIGOROL");
                    OnCODIGOROLChanged();
                }
            }
        }
        private global::System.Decimal _CODIGOROL;
        partial void OnCODIGOROLChanging(global::System.Decimal value);
        partial void OnCODIGOROLChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CODIGOMODULO
        {
            get
            {
                return _CODIGOMODULO;
            }
            set
            {
                if (_CODIGOMODULO != value)
                {
                    OnCODIGOMODULOChanging(value);
                    ReportPropertyChanging("CODIGOMODULO");
                    _CODIGOMODULO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CODIGOMODULO");
                    OnCODIGOMODULOChanged();
                }
            }
        }
        private global::System.Decimal _CODIGOMODULO;
        partial void OnCODIGOMODULOChanging(global::System.Decimal value);
        partial void OnCODIGOMODULOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> VISUALIZAR
        {
            get
            {
                return _VISUALIZAR;
            }
            set
            {
                OnVISUALIZARChanging(value);
                ReportPropertyChanging("VISUALIZAR");
                _VISUALIZAR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VISUALIZAR");
                OnVISUALIZARChanged();
            }
        }
        private Nullable<global::System.Boolean> _VISUALIZAR;
        partial void OnVISUALIZARChanging(Nullable<global::System.Boolean> value);
        partial void OnVISUALIZARChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> EDITAR
        {
            get
            {
                return _EDITAR;
            }
            set
            {
                OnEDITARChanging(value);
                ReportPropertyChanging("EDITAR");
                _EDITAR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EDITAR");
                OnEDITARChanged();
            }
        }
        private Nullable<global::System.Boolean> _EDITAR;
        partial void OnEDITARChanging(Nullable<global::System.Boolean> value);
        partial void OnEDITARChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("bienestarModel", "FK_ROL_MODULO_MODULO1", "MODULO")]
        public MODULO MODULO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MODULO>("bienestarModel.FK_ROL_MODULO_MODULO1", "MODULO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MODULO>("bienestarModel.FK_ROL_MODULO_MODULO1", "MODULO").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MODULO> MODULOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MODULO>("bienestarModel.FK_ROL_MODULO_MODULO1", "MODULO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MODULO>("bienestarModel.FK_ROL_MODULO_MODULO1", "MODULO", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("bienestarModel", "FK_ROL_MODULO_ROL", "ROL")]
        public ROL ROL
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ROL>("bienestarModel.FK_ROL_MODULO_ROL", "ROL").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ROL>("bienestarModel.FK_ROL_MODULO_ROL", "ROL").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ROL> ROLReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ROL>("bienestarModel.FK_ROL_MODULO_ROL", "ROL");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ROL>("bienestarModel.FK_ROL_MODULO_ROL", "ROL", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bienestarModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto sysdiagram.
        /// </summary>
        /// <param name="name">Valor inicial de la propiedad name.</param>
        /// <param name="principal_id">Valor inicial de la propiedad principal_id.</param>
        /// <param name="diagram_id">Valor inicial de la propiedad diagram_id.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bienestarModel", Name="USUARIO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class USUARIO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto USUARIO.
        /// </summary>
        /// <param name="cODIGOUSUARIO">Valor inicial de la propiedad CODIGOUSUARIO.</param>
        /// <param name="cONTRASENAANTERIOR">Valor inicial de la propiedad CONTRASENAANTERIOR.</param>
        /// <param name="eSTADOUSUARIO">Valor inicial de la propiedad ESTADOUSUARIO.</param>
        /// <param name="uSUARIO1">Valor inicial de la propiedad USUARIO1.</param>
        public static USUARIO CreateUSUARIO(global::System.Decimal cODIGOUSUARIO, global::System.String cONTRASENAANTERIOR, global::System.Boolean eSTADOUSUARIO, global::System.String uSUARIO1)
        {
            USUARIO uSUARIO = new USUARIO();
            uSUARIO.CODIGOUSUARIO = cODIGOUSUARIO;
            uSUARIO.CONTRASENAANTERIOR = cONTRASENAANTERIOR;
            uSUARIO.ESTADOUSUARIO = eSTADOUSUARIO;
            uSUARIO.USUARIO1 = uSUARIO1;
            return uSUARIO;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CODIGOUSUARIO
        {
            get
            {
                return _CODIGOUSUARIO;
            }
            set
            {
                if (_CODIGOUSUARIO != value)
                {
                    OnCODIGOUSUARIOChanging(value);
                    ReportPropertyChanging("CODIGOUSUARIO");
                    _CODIGOUSUARIO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CODIGOUSUARIO");
                    OnCODIGOUSUARIOChanged();
                }
            }
        }
        private global::System.Decimal _CODIGOUSUARIO;
        partial void OnCODIGOUSUARIOChanging(global::System.Decimal value);
        partial void OnCODIGOUSUARIOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NOMBREUSUARIO
        {
            get
            {
                return _NOMBREUSUARIO;
            }
            set
            {
                OnNOMBREUSUARIOChanging(value);
                ReportPropertyChanging("NOMBREUSUARIO");
                _NOMBREUSUARIO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NOMBREUSUARIO");
                OnNOMBREUSUARIOChanged();
            }
        }
        private global::System.String _NOMBREUSUARIO;
        partial void OnNOMBREUSUARIOChanging(global::System.String value);
        partial void OnNOMBREUSUARIOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CEDULAUSUARIO
        {
            get
            {
                return _CEDULAUSUARIO;
            }
            set
            {
                OnCEDULAUSUARIOChanging(value);
                ReportPropertyChanging("CEDULAUSUARIO");
                _CEDULAUSUARIO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CEDULAUSUARIO");
                OnCEDULAUSUARIOChanged();
            }
        }
        private global::System.String _CEDULAUSUARIO;
        partial void OnCEDULAUSUARIOChanging(global::System.String value);
        partial void OnCEDULAUSUARIOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CONTRASENAANTERIOR
        {
            get
            {
                return _CONTRASENAANTERIOR;
            }
            set
            {
                OnCONTRASENAANTERIORChanging(value);
                ReportPropertyChanging("CONTRASENAANTERIOR");
                _CONTRASENAANTERIOR = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CONTRASENAANTERIOR");
                OnCONTRASENAANTERIORChanged();
            }
        }
        private global::System.String _CONTRASENAANTERIOR;
        partial void OnCONTRASENAANTERIORChanging(global::System.String value);
        partial void OnCONTRASENAANTERIORChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CONTRASENAACTUAL
        {
            get
            {
                return _CONTRASENAACTUAL;
            }
            set
            {
                OnCONTRASENAACTUALChanging(value);
                ReportPropertyChanging("CONTRASENAACTUAL");
                _CONTRASENAACTUAL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CONTRASENAACTUAL");
                OnCONTRASENAACTUALChanged();
            }
        }
        private global::System.String _CONTRASENAACTUAL;
        partial void OnCONTRASENAACTUALChanging(global::System.String value);
        partial void OnCONTRASENAACTUALChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TIPOUSUARIO
        {
            get
            {
                return _TIPOUSUARIO;
            }
            set
            {
                OnTIPOUSUARIOChanging(value);
                ReportPropertyChanging("TIPOUSUARIO");
                _TIPOUSUARIO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TIPOUSUARIO");
                OnTIPOUSUARIOChanged();
            }
        }
        private global::System.String _TIPOUSUARIO;
        partial void OnTIPOUSUARIOChanging(global::System.String value);
        partial void OnTIPOUSUARIOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ESTADOUSUARIO
        {
            get
            {
                return _ESTADOUSUARIO;
            }
            set
            {
                OnESTADOUSUARIOChanging(value);
                ReportPropertyChanging("ESTADOUSUARIO");
                _ESTADOUSUARIO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ESTADOUSUARIO");
                OnESTADOUSUARIOChanged();
            }
        }
        private global::System.Boolean _ESTADOUSUARIO;
        partial void OnESTADOUSUARIOChanging(global::System.Boolean value);
        partial void OnESTADOUSUARIOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USUARIO1
        {
            get
            {
                return _USUARIO1;
            }
            set
            {
                OnUSUARIO1Changing(value);
                ReportPropertyChanging("USUARIO1");
                _USUARIO1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USUARIO1");
                OnUSUARIO1Changed();
            }
        }
        private global::System.String _USUARIO1;
        partial void OnUSUARIO1Changing(global::System.String value);
        partial void OnUSUARIO1Changed();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("bienestarModel", "ACTIVIDAD_USUARIO", "ACTIVIDAD")]
        public EntityCollection<ACTIVIDAD> ACTIVIDADs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ACTIVIDAD>("bienestarModel.ACTIVIDAD_USUARIO", "ACTIVIDAD");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ACTIVIDAD>("bienestarModel.ACTIVIDAD_USUARIO", "ACTIVIDAD", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("bienestarModel", "USUARIO_ROL", "ROL")]
        public EntityCollection<ROL> ROLs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ROL>("bienestarModel.USUARIO_ROL", "ROL");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ROL>("bienestarModel.USUARIO_ROL", "ROL", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
